version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      #KAFKA_CREATE_TOPICS: "Topic1:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # https://stackoverflow.com/questions/42998859/kafka-server-configuration-listeners-vs-advertised-listeners
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
